### ISSUE TITLE
Error 'DISALLOWED_INTENTS'

### ISSUE THREAD

**Issue by AvalibeHuman** [Nuggies-bot/buttonroles-example#3]
this is my log:
SocketManager.js:244
        throw new Error(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\username\Downloads\buttonroles-example-13\buttonroles-example-13\node_modules\discord.js\src\client\websocket\WebSocketManager.js:244:15)
    at async Client.login (C:\Users\username\Downloads\buttonroles-example-13\buttonroles-example-13\node_modules\discord.js\src\client\Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}

**Comment by face-hh** [comment]
L + ratio

**Comment by Assassin-1234** [comment]
This is not an issue in the code, either remove the disabled intents from the code or enable them through the developers portal.
